list: $/offline/microcart/models/paymentmethod/columns.yaml
modelClass: OFFLINE\MicroCart\Models\PaymentMethod
title: PaymentMethods
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'offline/microcart/paymentmethods/update/:id'
