# ===================================
#  Relation Behavior Config
# ===================================

taxes:
    label: 'offline.microcart::lang.common.taxes'
    view:
        list: $/offline/microcart/models/tax/columns.yaml
        toolbarButtons: add|create|remove
    manage:
        form: $/offline/microcart/models/tax/fields.yaml
        recordsPerPage: 10
    deferredBinding: true