plugin:
    name: 'offline.microcart::lang.plugin.name'
    description: 'offline.microcart::lang.plugin.description'
    author: OFFLINE
    icon: oc-icon-shopping-cart
    homepage: 'https://github.com/OFFLINE-GmbH/oc-microcart-plugin'
